apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-cfg-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc
  resources:
    requests:
      storage: 1Gi